### ISSUE TITLE
Login endpoint

### ISSUE THREAD

**Issue by mandala21** [mandala21/blinder#6]
# feature

Build end point for login. Login must have return JWT token for user

**Comment by ashvinimore** [comment]
I want to give it a try. Can you assign this task to me?

**Comment by mandala21** [comment]
Yes, remember i want use JWT.

I used previous this https://jpadilla.github.io/django-rest-framework-jwt/. If you dont want use no have a problem. Feel free for use any packed

**Comment by ashvinimore** [comment]
Thanks. I will try to use  https://jpadilla.github.io/django-rest-framework-jwt/.

**Comment by mandala21** [comment]
OK OK

If possible write some tests

**Comment by linneudm** [comment]
I think this issue was resolved in #16 , right?
