### ISSUE TITLE
Endpoint for register user

### ISSUE THREAD

**Issue by mandala21** [mandala21/blinder#7]
# feature
Create endpoint for register user

Initial fields:
* Username
* Name
* Email
* Phone

**Comment by djeni98** [comment]
I have some questions... 

**1 - Do you want to create an authentication system?**

Django already have an [authentication system](https://docs.djangoproject.com/en/3.1/topics/auth/). So you can choose to use it. It's easier in my opinion, I have some experience with Django and django_rest_framework and I have used their built-in auth system.

**2 - Do you want to use pure Django?**

As I have mentioned before, I have experience with django_rest_framework and I think it is good to build an API. But it is my personal opinion.

**Comment by mandala21** [comment]
Hello @djeni98 

Django rest framework is very good. I want use django + django rest framework.

For login i think that using JWT is the most secure and mordern.

I previous used djangorestframework-jwt for handle JWT 

feel free for create issue for add django rest framework to project or in this issue

**Comment by djeni98** [comment]
Ok. You can assign this issue to me.

**Comment by mandala21** [comment]
Ok. If possible can you write same test for method

**Comment by djeni98** [comment]
Hacktoberfest rules are changing (see PR digitalocean/hacktoberfest#596). Could you add "hacktoberfest" tag to your repository?

If you don't add it, your repo will not be participating in Hacktoberfest. 

(I picked this screenshot from my profile page in hacktoberfest profile site)
![image](https://user-images.githubusercontent.com/25268297/95004081-dfb36a80-05bc-11eb-8c86-494da2cdd8f0.png)

**Comment by mandala21** [comment]
done, topic add
